disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "The Sad Horse"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "img/sad-horse-removebg-preview.png"
description = "The Sad Horse Blog - Cryptography, CTF Write-ups and Web Exploitation"
keywords = ["The Sad Horse", "TheSadHorse Blog", "Johan Blog", "Hugo Blowfish", "Cryptography", "CTF", "Write-ups", "Web Exploitation", "Security", "Penetration Testing", "RSA", "AES", "Symmetric Cipher"]

[params.author]
name = '''h4n13'''
image = "img/sad-horse.png"
# headline = "Life Shjt ðŸš¬"
bio = "I am not a dreamer"
links = [
  { twitter = "https://x.com/chunguabuon" },
  { telegram = "https://t.me/vanhoang37123" },
]