 
# Write up
[[main]]
name = "Writeups"
pageRef = "writeup"
identifier = "E2MNe2SQwl"
weight = 9_999
#--------------------------

[[main]]
name = "About Me"
pageRef = "profile"
weight = 10_000
#--------------------------

# Blog menu
[[main]]
name = "Blogs"
pageRef = "blog"
weight = 20


[[main]]
name = "Symmetric Cipher"
parent = "Blogs"
weight = 20
pageRef = "blog/symmetric-cipher"

[[main]]
name = "RSA"
parent = "Blogs"
weight = 20
pageRef = "blog/rsa"
 
# -------------------------

#Author

#----------------------------


 
#-------------------------

[[footer]]
none = "none"
